//作为IDE提示用
export default class SoftwareItem {
    Name;
    ServerName;
    DirName;
    EtcList;
    ServerProcessPath;
    ConfPath;
    ServerConfPath;
    Type;
    IsMacApp;
    RemoteIsCommonPlatform;
    RemoteArchiveExt;
    ShellServerProcess;
    CanDelete;
    Icon;
    Desc;
    Installed;
}
