export const APP_NAME = 'EasyEnv'
export const WIN_CORE_PATH_NAME = 'core'
export const MAC_CORE_PATH_NAME = 'Core'
export const MAC_USER_CORE_PATH = '/Applications/EasyEnv/'
export const INIT_FILE_NAME = 'init.init'
export const SOFTWARE_DEFAULT_TYPE = 'Server'
export const CONF_INDENT = '    '
export const STATIC_WEB_NAME = '纯静态'